import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const id = () => integer("id").primaryKey({ autoIncrement: true });
const createdAt = () => integer("createdAt", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`);
const updatedAt = () => integer("updatedAt", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`).$onUpdate(() => new Date());
const bool = (name: string, defaultValue: boolean) => integer(name, { mode: "boolean" }).notNull().default(defaultValue);

export const users = sqliteTable("users", {
  id: id(), email: text("email").notNull().unique(), passwordHash: text("passwordHash"), googleId: text("googleId").unique(), name: text("name"), loginMethod: text("loginMethod"), role: text("role", { enum: ["user", "admin"] }).notNull().default("user"), avatarUrl: text("avatarUrl"), phone: text("phone"), company: text("company"), address: text("address"), status: text("status", { enum: ["lead", "active", "inactive"] }).notNull().default("active"), createdAt: createdAt(), updatedAt: updatedAt(), lastSignedIn: integer("lastSignedIn", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});

export const projects = sqliteTable("projects", { id: id(), title: text("title").notNull(), slug: text("slug").notNull().unique(), description: text("description").notNull(), category: text("category").notNull(), year: integer("year").notNull(), imageUrl: text("imageUrl"), liveUrl: text("liveUrl"), githubUrl: text("githubUrl"), technologies: text("technologies"), isFeatured: bool("isFeatured", false), isPublic: bool("isPublic", true), clientId: integer("clientId"), status: text("status", { enum: ["planning", "in_progress", "review", "completed", "on_hold"] }).notNull().default("planning"), progress: integer("progress").notNull().default(0), startDate: integer("startDate", { mode: "timestamp" }), deadline: integer("deadline", { mode: "timestamp" }), createdAt: createdAt(), updatedAt: updatedAt() });
export const services = sqliteTable("services", { id: id(), title: text("title").notNull(), description: text("description").notNull(), shortDescription: text("shortDescription"), icon: text("icon"), startingPrice: text("startingPrice"), features: text("features"), isFeatured: bool("isFeatured", false), sortOrder: integer("sortOrder").notNull().default(0), isActive: bool("isActive", true), createdAt: createdAt() });
export const certificates = sqliteTable("certificates", { id: id(), title: text("title").notNull(), issuer: text("issuer").notNull(), issueYear: integer("issueYear"), credentialId: text("credentialId"), imageUrl: text("imageUrl"), verifyUrl: text("verifyUrl"), description: text("description"), isFeatured: bool("isFeatured", false), isPublic: bool("isPublic", true), createdAt: createdAt() });
export const testimonials = sqliteTable("testimonials", { id: id(), clientName: text("clientName").notNull(), clientRole: text("clientRole"), company: text("company"), clientImageUrl: text("clientImageUrl"), quote: text("quote").notNull(), rating: integer("rating"), relatedProjectId: integer("relatedProjectId"), isFeatured: bool("isFeatured", false), isApproved: bool("isApproved", false), createdAt: createdAt() });
export const projectRequests = sqliteTable("projectRequests", { id: id(), userId: integer("userId"), name: text("name").notNull(), email: text("email").notNull(), phone: text("phone"), company: text("company"), projectName: text("projectName").notNull(), projectType: text("projectType").notNull(), description: text("description").notNull(), requiredFeatures: text("requiredFeatures"), budget: text("budget"), deadline: integer("deadline", { mode: "timestamp" }), referenceUrls: text("referenceUrls"), status: text("status", { enum: ["new", "reviewing", "accepted", "declined", "converted"] }).notNull().default("new"), createdAt: createdAt(), updatedAt: updatedAt() });
export const attachments = sqliteTable("attachments", { id: id(), uploaderId: integer("uploaderId"), requestId: integer("requestId"), projectId: integer("projectId"), changeRequestId: integer("changeRequestId"), milestoneId: integer("milestoneId"), deliverableId: integer("deliverableId"), filename: text("filename").notNull(), mimeType: text("mimeType").notNull(), size: integer("size"), storageKey: text("storageKey").notNull(), url: text("url").notNull(), createdAt: createdAt() });
export const changeRequests = sqliteTable("changeRequests", { id: id(), projectId: integer("projectId").notNull(), userId: integer("userId").notNull(), title: text("title").notNull(), description: text("description").notNull(), type: text("type", { enum: ["bug", "design_change", "content_change", "new_feature", "other"] }).notNull(), priority: text("priority", { enum: ["low", "medium", "high", "urgent"] }).notNull().default("medium"), status: text("status", { enum: ["open", "in_progress", "resolved", "closed"] }).notNull().default("open"), createdAt: createdAt(), updatedAt: updatedAt() });
export const changeRequestActivity = sqliteTable("changeRequestActivity", { id: id(), changeRequestId: integer("changeRequestId").notNull(), actorId: integer("actorId"), eventType: text("eventType").notNull(), body: text("body").notNull(), createdAt: createdAt() });
export const messages = sqliteTable("messages", { id: id(), projectId: integer("projectId"), senderId: integer("senderId").notNull(), recipientId: integer("recipientId"), body: text("body").notNull(), isRead: bool("isRead", false), createdAt: createdAt() });
export const meetingSlots = sqliteTable("meetingSlots", { id: id(), startTime: integer("startTime", { mode: "timestamp" }).notNull(), durationMinutes: integer("durationMinutes").notNull().default(30), status: text("status", { enum: ["available", "disabled", "booked"] }).notNull().default("available"), createdAt: createdAt() });
export const meetings = sqliteTable("meetings", { id: id(), projectId: integer("projectId"), clientId: integer("clientId"), slotId: integer("slotId"), title: text("title").notNull(), scheduledAt: integer("scheduledAt", { mode: "timestamp" }).notNull(), durationMinutes: integer("durationMinutes").notNull().default(30), meetingUrl: text("meetingUrl"), status: text("status", { enum: ["scheduled", "completed", "cancelled"] }).notNull().default("scheduled"), notes: text("notes"), guestName: text("guestName"), guestEmail: text("guestEmail"), guestPhone: text("guestPhone"), createdAt: createdAt() });
export const notifications = sqliteTable("notifications", { id: id(), userId: integer("userId").notNull(), type: text("type").notNull(), title: text("title").notNull(), body: text("body").notNull(), href: text("href"), isRead: bool("isRead", false), createdAt: createdAt() });

export const milestones = sqliteTable("milestones", { id: id(), projectId: integer("projectId").notNull(), title: text("title").notNull(), sortOrder: integer("sortOrder").notNull().default(0), status: text("status", { enum: ["pending", "in_progress", "completed"] }).notNull().default("pending"), progress: integer("progress").notNull().default(0), completedAt: integer("completedAt", { mode: "timestamp" }), createdAt: createdAt(), updatedAt: updatedAt() });
export const deliverables = sqliteTable("deliverables", { id: id(), projectId: integer("projectId").notNull(), milestoneId: integer("milestoneId"), title: text("title").notNull(), sortOrder: integer("sortOrder").notNull().default(0), status: text("status", { enum: ["pending", "in_progress", "awaiting_approval", "changes_requested", "completed"] }).notNull().default("pending"), reviewNote: text("reviewNote"), createdAt: createdAt(), updatedAt: updatedAt() });
export const agreements = sqliteTable("agreements", { id: id(), projectId: integer("projectId").notNull(), clientId: integer("clientId").notNull(), scope: text("scope"), timeline: text("timeline"), cost: text("cost"), revisions: text("revisions"), additionalWork: text("additionalWork"), cancellation: text("cancellation"), ipOwnership: text("ipOwnership"), terms: text("terms"), status: text("status", { enum: ["draft", "sent", "signed"] }).notNull().default("draft"), signedName: text("signedName"), signedAt: integer("signedAt", { mode: "timestamp" }), createdAt: createdAt(), updatedAt: updatedAt() });
export const projectActivity = sqliteTable("projectActivity", { id: id(), projectId: integer("projectId").notNull(), actorId: integer("actorId"), eventType: text("eventType").notNull(), body: text("body").notNull(), createdAt: createdAt() });
export const experience = sqliteTable("experience", { id: id(), title: text("title").notNull(), organization: text("organization").notNull(), type: text("type"), startDate: integer("startDate", { mode: "timestamp" }), endDate: integer("endDate", { mode: "timestamp" }), description: text("description"), logoUrl: text("logoUrl"), skills: text("skills"), isCurrent: bool("isCurrent", false), isFeatured: bool("isFeatured", false), isPublic: bool("isPublic", true), sortOrder: integer("sortOrder").notNull().default(0), createdAt: createdAt(), updatedAt: updatedAt() });
export const skills = sqliteTable("skills", { id: id(), name: text("name").notNull(), category: text("category"), icon: text("icon"), sortOrder: integer("sortOrder").notNull().default(0), isPublic: bool("isPublic", true), createdAt: createdAt() });
export const aboutProfile = sqliteTable("aboutProfile", { id: id(), name: text("name"), headline: text("headline"), bio: text("bio"), profileImageUrl: text("profileImageUrl"), email: text("email"), location: text("location"), socialLinks: text("socialLinks"), careerFocus: text("careerFocus"), updatedAt: updatedAt() });
export const clientNotes = sqliteTable("clientNotes", { id: id(), clientId: integer("clientId").notNull(), authorId: integer("authorId"), body: text("body").notNull(), createdAt: createdAt() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Project = typeof projects.$inferSelect; export type ProjectRequest = typeof projectRequests.$inferSelect;
export type Milestone = typeof milestones.$inferSelect; export type Deliverable = typeof deliverables.$inferSelect; export type Agreement = typeof agreements.$inferSelect; export type ProjectActivity = typeof projectActivity.$inferSelect;
export type Experience = typeof experience.$inferSelect; export type Skill = typeof skills.$inferSelect; export type AboutProfile = typeof aboutProfile.$inferSelect; export type ClientNote = typeof clientNotes.$inferSelect;
export type MeetingSlot = typeof meetingSlots.$inferSelect; export type Meeting = typeof meetings.$inferSelect;
