import { FormEvent, useEffect, useState } from "react";
import { Loader2, CheckCircle2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import Shell from "@/components/DashboardShell";

type AboutForm = { name: string; headline: string; bio: string; profileImageUrl: string; email: string; location: string; careerFocus: string; socialLinks: string };

const emptyForm: AboutForm = { name: "", headline: "", bio: "", profileImageUrl: "", email: "", location: "", careerFocus: "", socialLinks: "" };

export default function AdminAbout() { const about = trpc.admin.about.get.useQuery(); const [saved, setSaved] = useState(false); const update = trpc.admin.about.update.useMutation({ onSuccess: () => { about.refetch(); setSaved(true); setTimeout(() => setSaved(false), 2000); } }); const [form, setForm] = useState<AboutForm>(emptyForm); const [hydrated, setHydrated] = useState(false); useEffect(() => { if (about.data && !hydrated) { setForm({ name: about.data.name ?? "", headline: about.data.headline ?? "", bio: about.data.bio ?? "", profileImageUrl: about.data.profileImageUrl ?? "", email: about.data.email ?? "", location: about.data.location ?? "", careerFocus: about.data.careerFocus ?? "", socialLinks: about.data.socialLinks ?? "" }); setHydrated(true); } }, [about.data, hydrated]); const submit = (e: FormEvent) => { e.preventDefault(); update.mutate(form); }; return <Shell admin><div className="admin-page-wrap"><div className="dashboard-heading compact"><div><p className="section-kicker">/ PORTFOLIO</p><h1>ABOUT<br /><span>& PROFILE.</span></h1></div></div>{about.isPending ? <div className="admin-form"><Loader2 className="spin" size={20} /></div> : <form className="project-form admin-form" onSubmit={submit}><div className="form-grid"><label>NAME<input className="form-input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>HEADLINE<input className="form-input" value={form.headline} onChange={(e) => setForm({ ...form, headline: e.target.value })} /></label><label>EMAIL<input className="form-input" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>LOCATION<input className="form-input" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>CAREER FOCUS<input className="form-input" value={form.careerFocus} onChange={(e) => setForm({ ...form, careerFocus: e.target.value })} placeholder="AI Engineering" /></label><label>PROFILE IMAGE URL<input className="form-input" value={form.profileImageUrl} onChange={(e) => setForm({ ...form, profileImageUrl: e.target.value })} /></label></div><label>BIO<textarea className="form-input form-textarea" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /></label><label>SOCIAL LINKS<textarea className="form-input form-textarea" value={form.socialLinks} onChange={(e) => setForm({ ...form, socialLinks: e.target.value })} placeholder={"GitHub: https://github.com/...\nLinkedIn: https://linkedin.com/in/..."} /></label><button className="button button-accent" disabled={update.isPending}>{update.isPending ? <Loader2 className="spin" size={16} /> : saved ? <CheckCircle2 size={16} /> : null} {update.isPending ? "SAVING..." : saved ? "SAVED" : "SAVE"}</button></form>}</div></Shell>; }
